// src/stateMachine/definedStates.ts

export enum EncoderStates {
    INIT = 'INIT',
    OPTIMIZE_COMPRESSION_STRATEGY = 'OPTIMIZE_COMPRESSION_STRATEGY',
    READ_INPUT_FILE = 'READ_INPUT_FILE',
    COMPRESS_DATA = 'COMPRESS_DATA',
    ENCRYPT_DATA = 'ENCRYPT_DATA',
    GENERATE_CHECKSUM = 'GENERATE_CHECKSUM',
    CHECK_INPUT_PNG_CAPACITY = 'CHECK_INPUT_PNG_CAPACITY',
    SPLIT_DATA = 'SPLIT_DATA',
    ANALYZE_PNG_CAPACITIES = 'ANALYZE_PNG_CAPACITIES',
    DISTRIBUTE_CHUNKS = 'DISTRIBUTE_CHUNKS',
    INJECT_CHUNKS = 'INJECT_CHUNKS',
    CREATE_DISTRIBUTION_MAP = 'CREATE_DISTRIBUTION_MAP',
    INJECT_DISTRIBUTION_MAP = 'INJECT_DISTRIBUTION_MAP',
    WRITE_HUMAN_READABLE_MAP = 'WRITE_HUMAN_READABLE_MAP',
    VERIFY_ENCODING = 'VERIFY_ENCODING',
    COMPLETED = 'COMPLETED',
    ERROR = 'ERROR',
}

export enum DecoderStates {
    INIT = 'INIT',
    READ_MAP = 'READ_MAP',
    EXTRACT_CHUNKS = 'EXTRACT_CHUNKS',
    ASSEMBLE_DATA = 'ASSEMBLE_DATA',
    VERIFY_DECRYPT = 'VERIFY_DECRYPT',
    DECOMPRESS = 'DECOMPRESS',
    WRITE_OUTPUT = 'WRITE_OUTPUT',
    COMPLETED = 'COMPLETED',
    ERROR = 'ERROR',
}
